### ISSUE TITLE
he ipv6隧道能免登chatgpt web吗？

### ISSUE THREAD

**Issue by gordonchanfz** [oliverkirk-sudo/ipv6-pool-tool-socks#2]

**Comment by gordonchanfz** [comment]
试了下，生成的ipv6当节点，可以访问chatgpt，但是用在一些逆向的项目里报错，比如这个项目https://github.com/aurora-develop/aurora，能分享一下使用成功的项目吗？我交叉验证下，看看是什么问题。

**Comment by oliverkirk-sudo** [comment]
这个项目我就写着玩玩的，只在chatgpt上用过，别的场景没有使用

**Comment by gordonchanfz** [comment]
我已经自己折腾实现了，没用那个逆向的项目。he ipv6隧道可用，实现同一个ip入口，不同ipv6落地,访问chatgpt，稳定性尙未知。
